### ISSUE TITLE
homebridge-wiser stops responding to homekit

### ISSUE THREAD

**Issue by SteveHalliday** [paulw11/homebridge-wiser#5]
Hello

I have setup homebridge-wiser on a raspberry pi 3 using the guide written by Gary McDougall

https://www.youtube.com/watch?v=OMFv0r23cgE

but installing home-bridge-wiser instead of hombridge-cbus, and configuring the json.config for a wiser2 connection as per your github post.

This all worked great, however after a few days, the homebridge stops responding to the homekit app on all my devices (iPhone, iPad) The app just says everything is not responding.

If I remove the homebridge accessory from the homekit app and then add it again, it will work again for a day or so then the same problem occurs. I have tried the obvious of rebooting the Raspberry but nothing seems to fix the problem except removing / adding accessory as above.

I have attached to this post the logs from homebridge. 

![img_1677](https://user-images.githubusercontent.com/33366704/32514309-7b6f9ade-c461-11e7-8456-3449950fc7fc.jpg)

Wondering if anyone has any ideas as to what could be going wrong please :)

**Comment by paulw11** [comment]
Does the problem go away if you remove Homebridge-wiser?  

I am running Homebridge on a Raspberry Pi and it runs without any problems.

You could try changing the "username" MAC address in the home bridge config file; It seems that sometimes homekit needs to see a whole new accessory in order to clear up glitches; I had this problem when I upgraded to iOS 11.
