### ISSUE TITLE
REQUEST: Add support for blinds / curtains

### ISSUE THREAD

**Issue by xJARiD** [paulw11/homebridge-wiser#7]
Is there any upcoming support for curtain controller?

**Comment by paulw11** [comment]
Controlling a device like that would be fairly tricky; The closest HomeKit type is a "window" which has a current position and a target position, which is a percentage open.  This doesn't map very closely to a 3 button open/close/stop type of set up that you have since it will require timing to try and set the position of the screen and there is no positional feedback from the screen.  

You might do better with some Logic in the Wiser itself.

**Comment by xJARiD** [comment]
The blinds work same as light / dimmable light .. I’m just hoping I could get the icon that represents it as such. There’s no timing required.

As for the projector screen, it’s wired like a bell press. No timing required. 

I might try forking your code, but I wouldn’t know where to start!

Do you take bribes? Can I offer you some $$ :)

**Comment by paulw11** [comment]
Unfortunately the way that Homebridge works is that plugins, such as mine, need to expose accessories based on pre-defined HomeKit accessory types.  This is what controls the icon that is shown in the Home app.  

In theory the shutter relay in proportional mode could be mapped to a window object.

Your up/down/stop is trickier since there are three interconnected group addresses that you want map to a single accessory in HomeKit.

**Comment by xJARiD** [comment]
TBH, with the projector screen, I never use the stop button .. it’s programmed on the eDLT, so don’t really need it on HomeKit. I’ve mapped it to a scene that comes through homebridge anywho. 

It’s the other blinds that I control through HomeKit. Just want the blind icon (or window).
Not really fussed if it’s controlled with percentage or not.
